<?php

    if (session()->get('_status_logout')){
        session()->put('_msg_login', 'Logout efetuado com sucesso!');
        session()->forget('_status_logout');

    } elseif(session()->get('_erro_login')){
        session()->put('_msg_login', 'Usuário ou senha inválidos!');

    } elseif(session()->get('_erro_acesso')) {
        session()->put('_msg_login', 'Tivemos um erro imprevisto, por favor, acesse novamente!');
        session()->forget('_erro_acesso');

    } else{
        session()->put('_msg_login', 'Entre com seu login e senha!');
    }

    if (session()->get('_pag_login')){

        if(session()->get('_erro_login') || session()->get('_erro_acesso')): ?>
            <div class="alert alert-danger" role="alert"><?= session()->getAndRemove('_msg_login'); ?></div>
        <?php else: ?>
            <div class="alert alert-primary" role="alert"><?= session()->getAndRemove('_msg_login'); ?></div>
        <?php endif;

        session()->forget('_pag_login');
        session()->forget('_erro_login');

    } elseif(!session()->get('_user_status')){

        session()->forget('_pag_login');
        session()->forget('_erro_login');

        redirect()->route('login.index');
    }
?>

<head>
        <meta charset="utf-8">
        <meta name="robots" content="noindex,nofollow">
        <meta name="description" content="Processo seletivo UP ESTATE - Daniel Viana">
        <meta name="author" content="Isna Nur Azis, Compnum">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Processo seletivo UP ESTATE - Daniel Viana</title>

        <!-- start: Css -->
        <link rel="stylesheet" type="text/css" href="<?=assets()->css('bootstrap.min.css')?>">
        <!-- plugins -->
        <link rel="stylesheet" type="text/css" href="<?=assets()->css('plugins/font-awesome.min.css')?>"/>
        <link rel="stylesheet" type="text/css" href="<?=assets()->css('plugins/summernote.css')?>"/>
        <link rel="stylesheet" type="text/css" href="<?=assets()->css('plugins/simple-line-icons.css')?>"/>
        <link rel="stylesheet" type="text/css" href="<?=assets()->css('plugins/animate.min.css')?>"/>
        <link rel="stylesheet" type="text/css" href="<?=assets()->css('plugins/datatables.bootstrap.min.css')?>"/>
        <link rel="stylesheet" type="text/css" href="<?=assets()->css('plugins/nouislider.min.css')?>"/>
        <link rel="stylesheet" type="text/css" href="<?=assets()->css('plugins/select2.min.css')?>"/>
        <link rel="stylesheet" type="text/css" href="<?=assets()->css('plugins/ionrangeslider/ion.rangeSlider.css')?>"/>
        <link rel="stylesheet" type="text/css" href="<?=assets()->css('plugins/ionrangeslider/ion.rangeSlider.skinFlat.css')?>"/>
        <link rel="stylesheet" type="text/css" href="<?=assets()->css('plugins/bootstrap-material-datetimepicker.css')?>"/>
        <link rel="stylesheet" type="text/css" href="<?=assets()->css('plugins/dropzone.css')?>"/>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/shepherd.js@8.3.1/dist/css/shepherd.css"/>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap">

        <link href="<?=assets()->css('style.css')?>" rel="stylesheet">
        <!-- end: Css -->

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>