        <nav class="navbar navbar-default header navbar-fixed-top">
            <div class="col-md-12 nav-wrapper">
                <div class="navbar-header" style="width:100%;">
                    <div class="opener-left-menu is-open">
                        <span class="top"></span>
                        <span class="middle"></span>
                        <span class="bottom"></span>
                    </div>
                    <a href="index" class="navbar-brand">
                        <?=NOME_SITE?>
                    </a>

                    <ul class="nav navbar-nav navbar-right user-nav">
                        <li class="user-name"><span><?=  session()->get('_user_nome')?></span></li>
                        <li class="dropdown avatar-dropdown">
                            <img src="<?= assets()->img('avatar_user.jpg') ?>" class="img-circle avatar" alt="user name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"/>
                            <ul class="dropdown-menu user-dropdown">
                                <li><a href="<?=  url()->route('login.logout');?>"><span class="fa fa-power-off"></span> Sair</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>     