            <div id="left-menu">
                <div class="sub-left-menu scroll">
                    <ul class="nav nav-list">
                        <li><div class="left-bg"></div></li>
                        <li class="active ripple"><a href="<?=url()->route('index')?>"><span class="fa fa-user"></span>Gerenciar Clientes</a></li>
                    </ul>
                </div>
            </div>